#!/bin/bash
# @author general  Zeus OPS with FBI NCA INTERPOL BARESKRIM POLRI

echo "
   ╔════════════════════════════════════════════╗
   ║                                            ║
   ║      ███████╗███████╗██╗   ██╗███████╗     ║
   ║      ╚══███╔╝██╔════╝██║   ██║██╔════╝     ║
   ║        ███╔╝ █████╗  ██║   ██║███████╗     ║
   ║       ███╔╝  ██╔══╝  ██║   ██║╚════██║     ║
   ║      ███████╗███████╗╚██████╔╝███████║     ║
   ║      ╚══════╝╚══════╝ ╚═════╝ ╚══════╝     ║
   ╚════════════════════════════════════════════╝
"


if [ "$#" -ne 3 ]; then
    echo -e "\e[31m[!] ERROR: Invalid number of arguments\e[0m"
    echo -e "\e[33m[*] Usage:\e[0m $(basename "$0") input.txt domain_ip.txt ips.txt"
    echo ""
    echo -e "\e[36mExample:\e[0m"
    echo "  $(basename "$0") targets.txt domains.txt ip_list.txt"
    exit 1
fi

input_file=$1
output_file=$2
ip_only_file=$3

if [ ! -e "$input_file" ]; then
    echo " Failed: File $input_file not found."
    exit 1
fi


temp_ip_list=$(mktemp)

while read -r domain; do
    ip=$(nslookup "$domain" | grep 'Address' | grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}\b' | awk 'NR==2{print}')
    if [ -n "$ip" ]; then
        echo " Domain: $domain, IP: $ip"
        echo "$domain => $ip" >> "$output_file"
        echo "$ip" >> "$temp_ip_list"
    else
        echo " Domain: $domain, IP: [ADDR ERROR]"
        echo "$domain => [ADDR ERROR]" >> "$output_file"
    fi
done < "$input_file"


sort -u "$temp_ip_list" > "$ip_only_file"
rm "$temp_ip_list"

echo ""
echo "Done!"
echo "Saved:"
echo " - Domain to IP map => $output_file"
echo " - Unique IPs only  => $ip_only_file"
